id: P000439
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-16 15:39:59.379244
source_metadata:
  id: bdr:W8LS19000
  title: ཤར་འཛམ་ཐང་པ་ངག་དབང་བློ་གྲོས་གྲགས་པའི་རྣམ་ཐར།
  author: ''
  volumes:
    9df0a794cd374ff38bb3b00ec18f9679:
      image_group_id: I8LS19002
      title: Volume 1 of shar 'dzam thang pa ngag dbang blo gros grags pa'i rnam thar/_jo
        nang dpe tshogs/_90
      volume_number: 1
      total_pages: 364
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
